apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yandex-odyssey.name" . }}
  labels:
    {{- include "yandex-odyssey.labels" . | nindent 4 }}
{{- if .Values.yandex_odyssey.annotations }}
  annotations:
  {{- if .Values.yandex_odyssey.annotations }}
    {{- .Values.yandex_odyssey.annotations | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "yandex-odyssey.selectorLabels" . | nindent 6 }}
  #https://github.com/yandex/odyssey/issues/421
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "yandex-odyssey.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if or (not .Values.yandex_odyssey.existingSecret) .Values.yandex_odyssey.podAnnotations }}
      annotations:
      {{- if .Values.yandex_odyssey.podAnnotations }}
        {{- .Values.yandex_odyssey.podAnnotations | toYaml | nindent 8 }}
      {{- end }}
      {{- if not .Values.yandex_odyssey.existingSecret }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- end }}
    {{- end }}
    spec:
      serviceAccountName: {{ include "yandex-odyssey.serviceAccount" . }}
    {{ if .Values.yandex_odyssey.securityContext }}
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
    {{ end }}
      volumes:
      {{- include "yandex-odyssey.certsVolume" . | nindent 6 }}
        - name: yandex-odyssey-cm
          configMap:
            name: yandex-odyssey-cm
            defaultMode: 420
      containers:
      - name: {{ .Chart.Name }}
        image: {{ include "yandex-odyssey.image" . }}
        imagePullPolicy: IfNotPresent
        terminationMessagePath: /dev/termination-log
        ports:
        - name: main
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        {{- include "yandex-odyssey.certsMount" . | nindent 8 }}
          
        env:
        {{- range $key, $val := .Values.yandex_odyssey.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
        {{- include "yandex-odyssey.certsEnv" . | nindent 8 }}
        envFrom:
        - secretRef:
            name: {{ include "yandex-odyssey.name" . }}
        terminationMessagePolicy: File
        resources:
          {{- toYaml .Values.yandex_odyssey.resources | nindent 12 }}
        volumeMounts:
          - name: yandex-odyssey-cm
            mountPath: /home/appuser/odyssey/odyssey.conf
            subPath: odyssey.conf
      - name: yandex-odyssey-exporter
        image: {{ include "yandex-odyssey-exporter.image" . }}
        imagePullPolicy: IfNotPresent
        env:
        - name: ODYSSEY_EXPORTER_PORT
          value: {{ .Values.yandex_odyssey_exporter.host }}:{{ .Values.yandex_odyssey_exporter.port }}
        - name: ODYSSEY_CONN_STRING
          value: {{ include "odyssey-exporter.string" . }}
        resources:
          {{- toYaml .Values.yandex_odyssey_exporter.resources | nindent 12 }}
        ports:
        - name: http-metrics
          containerPort: 9127
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 10  
      imagePullSecrets:
      - name: {{ .Values.common.imagePullSecrets }}
