apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yandex-odyssey.name" . }}
  labels:
    {{- include "yandex-odyssey.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "secrets.odyssey" . | nindent 2 }}