{{ if .Values.yandex_odyssey.serviceAccount.create }}
# Service account the client will use to reset the deployment,
# by default the pods running inside the cluster can do no such things.
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "yandex-odyssey.serviceAccount" . }}
  labels:
    {{- include "yandex-odyssey.labels" . | nindent 4 }}
{{ end }}