apiVersion: v1
kind: Service
metadata:
  name: {{ include "yandex-odyssey.fullname" . }}
  labels:
    {{- include "yandex-odyssey.labels" . | nindent 4 }}
spec:
  type: {{ .Values.yandex_odyssey.service.type }}
  ports:
    - port: {{ .Values.yandex_odyssey.service.port }}
      targetPort: {{ .Values.yandex_odyssey.service.targetPort }}
      protocol: TCP
      name: main
    - port: {{ .Values.yandex_odyssey_exporter.service.port }}
      targetPort: {{ .Values.yandex_odyssey_exporter.service.targetPort }}
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "yandex-odyssey.selectorLabels" . | nindent 4 }}

